### ISSUE TITLE
Image preprocessing

### ISSUE THREAD

**Issue by IandRover** [allenai/satlaspretrain_models#11]
Hello,

Thank you for your excellent work. I'm interested in understanding your data preprocessing methodology, particularly how you convert the original dataset into JPEG files. We're developing a benchmark dataset intended to integrate seamlessly with the SatlasPretrain model. 

Our current process involves downloading images from Google Earth Engine, where the original pixel values for Sentinel-2 data range from 0 to 60,000. In light of this, I have two specific questions:
1. Which platform do you use to access the Sentinel-2 images?
2. What preprocessing steps do you take to convert the original values to the 0-255 range?

Thank you for your time and assistance.

**Comment by favyen2** [comment]
We access the Sentinel-2 data from https://cloud.google.com/storage/docs/public-datasets/sentinel-2 (on free Google Cloud Storage bucket) and the normalization is detailed at https://github.com/allenai/satlas/blob/main/Normalization.md#sentinel-2-images
