### ISSUE TITLE
Swin-T Multi-image sentinel-2

### ISSUE THREAD

**Issue by JohnMBrandt** [allenai/satlaspretrain_models#4]
Loving your work! I'm a data scientist at the World Resources Institute, where I lead our sentinel-2 based tree-cover mapping: https://www.sciencedirect.com/science/article/pii/S0034425723001256

I have taken the multi-image Swin-B Sentinel-2 model and fine-tuned it by adding a parallel encoder U-Net++ for higher-resolution features, since the Swin-B itself generated very blurry segmentation outputs.

The results of the Swin-B + U-Net++ look really good, but I'm unable to deploy the model since my data product is 6 years across 5 billion ha / year. Having a Swin-T instead of a Swin-B would be very helpful for fitting the model into the inference architecture that I have set up. 

Do you have any plans to release a Swin-T Multi-image Sentinel-2 model? Happy to make a PR with my edits to incorporate a parallel U-Net++ if its helpful.

**Comment by piperwolters** [comment]
Hi! Thanks for your interest in the project!

We may release additional weights depending on demand and resources. 
For now - I just updated the weights table to include Sentinel-2 Swin-T Single-Image multispectral model (before there was only the RGB model). So you could try fine-tuning one of the single-image models for multi-image. You'll just have to adjust the weight keys to include a "backbone." prefix.

**Comment by piperwolters** [comment]
@JohnMBrandt Hi, we just pushed additional pretrained models, including the Swin-Tiny multi-image [model].(https://github.com/allenai/satlaspretrain_models#available-pretrained-models)
