### ISSUE TITLE
[Bug] Required Long instead of Float cast for target tensor in Cross-Entropy based tasks ?

### ISSUE THREAD

**Issue by Bencpr** [allenai/satlaspretrain_models#5]
Hi there,

Pytorch's implementation of Cross Entropy requires target tensor to has dtype Long, otherwise throws `RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #2 'target'`.

In the **SimpleHead**'s forward call, there are dtype casts with `.float()` on targets tensor during cross-entropy loss computation in three tasks: 
- segment : https://github.com/allenai/satlaspretrain_models/blob/main/satlaspretrain_models/models/heads.py#L179 
- bin segment : https://github.com/allenai/satlaspretrain_models/blob/main/satlaspretrain_models/models/heads.py#L187
- multi label classif: https://github.com/allenai/satlaspretrain_models/blob/main/satlaspretrain_models/models/heads.py#L216  

Whereas in the classification task, dtype cast is done properly using `.to(torch.long)` : https://github.com/allenai/satlaspretrain_models/blob/main/satlaspretrain_models/models/heads.py#L206C82-L206C97 

One should cast target tensors using 
```
task_targets = torch.stack([target for target in targets], dim=0).long()
```

I can make a PR for this if needed!

Thanks,
Ben

**Comment by piperwolters** [comment]
Ah, good catch. I'll push a fix. Thank you!

**Comment by piperwolters** [comment]
This fix is included in [this PR](https://github.com/allenai/satlaspretrain_models/pull/7). Once the decoder head is working, will merge. Thanks again!

**Comment by piperwolters** [comment]
Merged [PR](https://github.com/allenai/satlaspretrain_models/commit/c791894afb27835d5731f276660482302d0e4a00).
